---
#
#    CentOS 7 (centos7) PHP56 Language (docker-compose.yml)
#    Copyright (C) 2016-2017 Stafli
#    Luís Pedro Algarvio
#    This file is part of the Stafli Application Stack.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Services
#
services:

  language_php56_centos7:
    labels:
      - "description=$PROJECT_NAME, $PROJECT_DESCRIPTION"
      - "maintainer=$PROJECT_AUTHORS_LPALGARVIO_NAME <$PROJECT_AUTHORS_LPALGARVIO_EMAIL>"
      - "org.label-schema.schema-version=1.0.0-rc.1"
      - "org.label-schema.name=$PROJECT_NAME"
      - "org.label-schema.description=$PROJECT_DESCRIPTION"
      - "org.label-schema.keywords=$PROJECT_KEYWORDS"
      - "org.label-schema.url=$PROJECT_URL"
      - "org.label-schema.license=$PROJECT_LICENSE"
      - "org.label-schema.vendor-name=$PROJECT_VENDOR_NAME"
      - "org.label-schema.vendor-email=$PROJECT_VENDOR_EMAIL"
      - "org.label-schema.vendor-website=$PROJECT_VENDOR_WEBSITE"
      - "org.label-schema.authors.lpalgarvio.name=$PROJECT_AUTHORS_LPALGARVIO_NAME"
      - "org.label-schema.authors.lpalgarvio.email=$PROJECT_AUTHORS_LPALGARVIO_EMAIL"
      - "org.label-schema.authors.lpalgarvio.homepage=$PROJECT_AUTHORS_LPALGARVIO_HOMEPAGE"
      - "org.label-schema.authors.lpalgarvio.role=$PROJECT_AUTHORS_LPALGARVIO_ROLE"
      - "org.label-schema.registry-url=$REGISTRY_URL"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-branch=$VCS_BRANCH"
      - "org.label-schema.os-id=$OS_ID"
      - "org.label-schema.os-version-id=$OS_VERSION_ID"
      - "org.label-schema.os-architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "${IMAGE_URL_PREFIX}:${IMAGE_TAG_PREFIX}${DISTRO_CENTOS7_VERSION}_${OS_RELEASE_ID}"
    build:
      context: "./dockerfiles"
      dockerfile: "${IMAGE_TAG_PREFIX}${DISTRO_CENTOS7_VERSION}.dockerfile"
      args:
        app_php_exts_core_dis: "mysql"
        app_php_exts_core_en: "mcrypt curl gd imap ldap mysqli mysqlnd odbc pdo pdo_mysql pdo_odbc opcache"
        app_php_exts_extra_dis: "xdebug xhprof"
        app_php_exts_extra_en: "igbinary msgpack yaml solr mongodb memcache memcached redis"
        app_php_global_log_level: "E_ALL"
        app_php_global_log_display: "On"
        app_php_global_log_file: "On"
        app_php_global_limit_timeout: "120"
        app_php_global_limit_memory: "134217728"
        app_fpm_global_user: "apache"
        app_fpm_global_group: "apache"
        app_fpm_global_home: "/var/www"
        app_fpm_global_log_level: "notice"
        app_fpm_global_limit_descriptors: "1024"
        app_fpm_global_limit_processes: "128"
        app_fpm_pool_id: "default"
        app_fpm_pool_user: "apache"
        app_fpm_pool_group: "apache"
        app_fpm_pool_listen_wlist: ""
        app_fpm_pool_listen_addr: "[::]"
        app_fpm_pool_listen_port: "9000"
        app_fpm_pool_limit_descriptors: "1024"
        app_fpm_pool_limit_backlog: "65536"
        app_fpm_pool_pm_method: "dynamic"
        app_fpm_pool_pm_max_children: "100"
        app_fpm_pool_pm_start_servers: "20"
        app_fpm_pool_pm_min_spare_servers: "10"
        app_fpm_pool_pm_max_spare_servers: "30"
        app_fpm_pool_pm_process_idle_timeout: "10s"
        app_fpm_pool_pm_max_requests: "5000"
    logging:
      driver: "json-file"
    volumes:
      - language_php56_centos7_data:/var/www
    ports:
      - "9000"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"

#
# Volumes
#
volumes:
  language_php56_centos7_data:
    driver: "local"

